In [ ]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

student_df = pd.DataFrame({
    'Student_ID': [1, 2, 3, 4, 5],
    'Performance_Level': ['Low', 'Medium', 'High', 'Medium', 'Low'],
    'Math_Score': [75, 85, 90, 78, 80],
    'English_Score': [82, 88, 95, 79, 85]
})
student_df

Student_ID Performance_Level  Math_Score  English_Score
0           1               Low          75             82
1           2            Medium          85             88
2           3              High          90             95
3           4            Medium          78             79
4           5               Low          80             85

In [ ]:
# Create an instance of OrdinalEncoder
ordinal_en = OrdinalEncoder(categories=[['Low', 'Medium', 'High']],
                            dtype=int)

# Apply ordinal encoding to the 'Performance_Level' column
student_df['Performance_Level'] = ordinal_en.fit_transform(student_df[['Performance_Level']])

student_df

Student_ID  Performance_Level  Math_Score  English_Score
0           1                  0          75             82
1           2                  1          85             88
2           3                  2          90             95
3           4                  1          78             79
4           5                  0          80             85

In [ ]:
from sklearn.preprocessing import LabelEncoder

student_df1 = pd.DataFrame({
    'Student_ID': [1, 2, 3, 4, 5],
    'Gender': ['Male', 'Female', 'Male', 'Male', 'Female'],
    'Math_Score': [75, 85, 90, 78, 80],
    'English_Score': [82, 88, 95, 79, 85]
})
student_df1

Student_ID  Gender  Math_Score  English_Score
0           1    Male          75             82
1           2  Female          85             88
2           3    Male          90             95
3           4    Male          78             79
4           5  Female          80             85

In [ ]:

label_en = LabelEncoder()

# Apply label encoding to the specified column
student_df1['Gender'] = label_en.fit_transform(student_df1['Gender'])
student_df1

Student_ID  Gender  Math_Score  English_Score
0           1       1          75             82
1           2       0          85             88
2           3       1          90             95
3           4       1          78             79
4           5       0          80             85

In [ ]:
# Create a sample fruit dataset
fruit_df = pd.DataFrame({
    'Fruit': ['Apple', 'Banana', 'Orange', 'Apple', 'Orange'],
    'Color': ['Red', 'Yellow', 'Orange', 'Green', 'Orange'],
    'Taste': ['Sweet', 'Sweet', 'Citrusy', 'Sweet', 'Citrusy'],
    'Price': [0.75, 0.25, 0.50, 1.00, 0.60]
})

# Display the original dataset
print("Original Dataset:")
print(fruit_df)

Original Dataset:
    Fruit   Color    Taste  Price
0   Apple     Red    Sweet   0.75
1  Banana  Yellow    Sweet   0.25
2  Orange  Orange  Citrusy   0.50
3   Apple   Green    Sweet   1.00
4  Orange  Orange  Citrusy   0.60


In [ ]:
# Apply one-hot encoding to the 'Fruit' and 'Taste' columns
en_fruit_df = pd.get_dummies(fruit_df,
                             columns=['Fruit', 'Taste'],
                              prefix=['Fr', 'Ta'],drop_first=True)

# Display the encoded dataset
print("\nEncoded Dataset:")
print(en_fruit_df)


Encoded Dataset:
    Color  Price  Fr_Apple  Fr_Banana  Fr_Orange  Ta_Citrusy  Ta_Sweet
0     Red   0.75         1          0          0           0         1
1  Yellow   0.25         0          1          0           0         1
2  Orange   0.50         0          0          1           1         0
3   Green   1.00         1          0          0           0         1
4  Orange   0.60         0          0          1           1         0


In [ ]:
en_fruit_df.shape

(5, 5)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)
# transform data
onehot = encoder.fit_transform(fruit_df)
print(onehot)

[[1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 1.]
 [0. 0. 1. 1. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


SCALING METHODS

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Create a sample student dataset
students_df = pd.DataFrame({
    'Student_ID': [1, 2, 3, 4, 5],
    'Math_Score': [75, 85, 90, 78, 80],
    'English_Score': [82, 88, 95, 79, 85]
})

print(students_df)

   Student_ID  Math_Score  English_Score
0           1          75             82
1           2          85             88
2           3          90             95
3           4          78             79
4           5          80             85


In [ ]:
# Create an instance of MinMaxScaler
scaler = MinMaxScaler()

students_scaled = scaler.fit_transform(students_df[['Math_Score', 'English_Score']])

# Create a DataFrame with the scaled columns
scaled_df = pd.DataFrame(students_scaled, columns=['Math_Score', 'English_Score'])

# Concatenate the scaled DataFrame with the original DataFrame
students_scaled_df = pd.concat([students_df, scaled_df], axis=1)

print(students_scaled_df)

   Student_ID  Math_Score  English_Score  Math_Score  English_Score
0           1          75             82    0.000000         0.1875
1           2          85             88    0.666667         0.5625
2           3          90             95    1.000000         1.0000
3           4          78             79    0.200000         0.0000
4           5          80             85    0.333333         0.3750


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Apply StandardScaler to the numerical columns
students_standardized = scaler.fit_transform(students_df[['Math_Score', 'English_Score']])

# Create a DataFrame with the standardized columns
standardized_df = pd.DataFrame(students_standardized,
                               columns=['St_Math_Score','St_English_Score'])

# Concatenate the standardized DataFrame with the original DataFrame
students_standardized_df = pd.concat([students_df, standardized_df], axis=1)

print("\nStandardized Dataset:")
print(students_standardized_df)


Standardized Dataset:
   Student_ID  Math_Score  English_Score  Standardized_Math_Score  \
0           1          75             82                -1.241971   
1           2          85             88                 0.639803   
2           3          90             95                 1.580691   
3           4          78             79                -0.677439   
4           5          80             85                -0.301084   

   Standardized_English_Score  
0                   -0.691939  
1                    0.400596  
2                    1.675221  
3                   -1.238207  
4                   -0.145671  


#Encoding and Scaling on IRIS dataset

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split


iris = load_iris()
data = iris.data
target =iris.target


In [ ]:
columns = ["sepal_length", "sepal_width", "petal_length", "petal_width"]
df_iris = pd.DataFrame(data, columns=columns)
df_iris["target"] = target

df_iris.head()

sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [ ]:
X_iris = df_iris.drop('target', axis=1)
y_iris = df_iris['target']

In [ ]:
X_train ,X_test , y_train , y_test = train_test_split(X_iris ,y_iris,
                                                      test_size =0.2,
                                                      random_state =42 )

In [ ]:
# Standardize the features using StandardScaler
scaler_iris = StandardScaler()
X_train_iris = scaler_iris.fit_transform(X_train)
X_train_iris

array([[-1.47393679,  1.20365799, -1.56253475, -1.31260282],
       [-0.13307079,  2.99237573, -1.27600637, -1.04563275],
       [ 1.08589829,  0.08570939,  0.38585821,  0.28921757],
       [-1.23014297,  0.75647855, -1.2187007 , -1.31260282],
       [-1.7177306 ,  0.30929911, -1.39061772, -1.31260282],
       [ 0.59831066, -1.25582892,  0.72969227,  0.95664273],
       [ 0.72020757,  0.30929911,  0.44316389,  0.4227026 ],
       [-0.74255534,  0.98006827, -1.27600637, -1.31260282],
       [-0.98634915,  1.20365799, -1.33331205, -1.31260282],
       [-0.74255534,  2.32160658, -1.27600637, -1.44608785],
       [-0.01117388, -0.80864948,  0.78699794,  0.95664273],
       [ 0.23261993,  0.75647855,  0.44316389,  0.55618763],
       [ 1.08589829,  0.08570939,  0.55777524,  0.4227026 ],
       [-0.49876152,  1.87442714, -1.39061772, -1.04563275],
       [-0.49876152,  1.4272477 , -1.27600637, -1.31260282],
       [-0.37686461, -1.47941864, -0.01528151, -0.24472256],
       [ 0.59831066, -0.

#Encoding & Scaling On Titanic dataset

In [ ]:
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler

# Load Titanic dataset from seaborn
titanic_data = sns.load_dataset('titanic')

# Display the first few rows of the dataset
print(titanic_data.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  


In [ ]:
columns_to_drop = ['deck', 'who',
                    'embark_town', 'alive',
                   'class', 'adult_male','alone']
titanic_data = titanic_data.drop(columns=columns_to_drop, axis=1)


In [ ]:
titanic_data.head()

survived  pclass     sex   age  sibsp  parch     fare embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [ ]:
titanic_data.isna().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
dtype: int64

In [ ]:
titanic_data['age'].fillna(titanic_data['age'].median(), inplace=True)
titanic_data['embarked'].fillna(titanic_data['embarked'].mode()[0], inplace=True)


In [ ]:
titanic_data.isna().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
dtype: int64

In [ ]:
# Select features and target variable
X = titanic_data.drop('survived', axis=1)
y = titanic_data['survived']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  891 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [ ]:
categorical_cols = ['sex', 'embarked']
X_train_onehot = pd.get_dummies(X_train, columns=categorical_cols, drop_first=True)
X_test_onehot = pd.get_dummies(X_test, columns=categorical_cols, drop_first=True)

In [ ]:
# Label encoding for remaining categorical variables (if any)
label_encoder = LabelEncoder()
for col in ['pclass', 'sibsp', 'parch']:
    X_train_onehot[col] = label_encoder.fit_transform(X_train_onehot[col])
    X_test_onehot[col] = label_encoder.transform(X_test_onehot[col])

In [ ]:
# Feature scaling for numerical variables
scaler = StandardScaler()
numerical_cols = ['age', 'fare']
X_train_onehot = scaler.fit_transform(X_train_onehot)
# X_test_onehot[numerical_cols] = scaler.transform(X_test_onehot[numerical_cols])

# Display the preprocessed training set
X_train_onehot.shape

(712, 8)

#Encoding & Scaling On IRIS dataset

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import LabelEncoder, OneHotEncoder# Load the Iris dataset
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['species'] = iris.target_names[iris.target]
iris_df['target'] = iris.target
# iris
# Display the original dataset
print("Original Iris Dataset:")
print(iris_df.head())


Original Iris Dataset:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  target  
0  setosa       0  
1  setosa       0  
2  setosa       0  
3  setosa       0  
4  setosa       0  


In [ ]:
# Apply Label Encoding to the 'species' column
label_encoder = LabelEncoder()
iris_df['species_encoded'] = label_encoder.fit_transform(iris_df['species'])

# Display the dataset with Label Encoding
print("\nDataset with Label Encoding:")
print(iris_df.head())


Dataset with Label Encoding:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  target  species_encoded  
0  setosa       0                0  
1  setosa       0                0  
2  setosa       0                0  
3  setosa       0                0  
4  setosa       0                0  


In [ ]:
iris_df['species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [ ]:
iris_df['target'].value_counts()

0    50
1    50
2    50
Name: target, dtype: int64

In [ ]:
iris_df['species_encoded'].value_counts()

0    50
1    50
2    50
Name: species_encoded, dtype: int64

In [ ]:
# Apply One-Hot Encoding to the 'species' column
onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded = onehot_encoder.fit_transform(iris_df[['species']])
onehot_df = pd.DataFrame(onehot_encoded, columns=label_encoder.classes_)

# Concatenate the One-Hot encoded DataFrame with the original DataFrame
# iris_onehot_df = pd.concat([iris_df, onehot_df], axis=1)

# Display the dataset with One-Hot Encoding
print("\nDataset with One-Hot Encoding:")
# print(iris_onehot_df.head())
onehot_df


Dataset with One-Hot Encoding:


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


setosa  versicolor  virginica
0       1.0         0.0        0.0
1       1.0         0.0        0.0
2       1.0         0.0        0.0
3       1.0         0.0        0.0
4       1.0         0.0        0.0
..      ...         ...        ...
145     0.0         0.0        1.0
146     0.0         0.0        1.0
147     0.0         0.0        1.0
148     0.0         0.0        1.0
149     0.0         0.0        1.0

[150 rows x 3 columns]