In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [4]:
x.ndim

1

In [5]:
x.shape

(5,)

In [6]:
type(x)

numpy.ndarray

In [8]:
a = [[1,2,3],[4,5,6]]
b = np.array(a)

In [9]:
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
b.ndim

2

In [11]:
b.shape

(2, 3)

In [12]:
b.size

6

In [14]:
np.array(a,dtype=float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
a[0]

[1, 2, 3]

In [16]:
a[1]

[4, 5, 6]

In [22]:
x = np.array([11,12,13,14])
x[0] + x[2]

24

In [23]:
x = np.array([11,12,13,14,15,16,17,19])
x[1:5]

array([12, 13, 14, 15])

In [24]:
x[4:]

array([15, 16, 17, 19])

In [25]:
x[1:7:2]

array([12, 14, 16])

In [26]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
arr[0]

array([1, 2, 3, 4, 5])

In [28]:
arr[1,1:4]

array([7, 8, 9])

In [29]:
x = np.array([11,12,13,14,15,16,17,19])

for i in x:
  print("number is ",i)

number is  11
number is  12
number is  13
number is  14
number is  15
number is  16
number is  17
number is  19


In [31]:
arr1 =([1,2,3,4])
arr2 =([5,6,7,8])

arr3 = np.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4 5 6 7 8]


In [33]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr1

array([[1, 2],
       [3, 4]])

In [34]:
arr2

array([[5, 6],
       [7, 8]])

In [37]:
arr3 = np.concatenate((arr1,arr2),axis=1)
arr3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [38]:
zer_arr = np.zeros((3,4))
zer_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
one_arr = np.ones((2,3),dtype=int)
one_arr

array([[1, 1, 1],
       [1, 1, 1]])

In [42]:
eye_arr = np.eye(3)
eye_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
full_arr = np.full((2,3),999)
full_arr

array([[999, 999, 999],
       [999, 999, 999]])

In [45]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [46]:
arr = np.array([[3, 12, 4], [5, 10, 1]])

print(np.sort(arr))

[[ 3  4 12]
 [ 1  5 10]]


In [50]:
arr = np.array([10,23,43,52,89,22,90])
newarr = np.array_split(arr,4)
print(newarr)

[array([10, 23]), array([43, 52]), array([89, 22]), array([90])]


In [51]:
newarr[0]

array([10, 23])

In [52]:
newarr[1]

array([43, 52])

In [57]:
np.random.rand()

0.3531295654390223

In [61]:
np.random.rand(4,2)

array([[0.96169501, 0.80808541],
       [0.70213575, 0.1007894 ],
       [0.56897861, 0.66681558],
       [0.59644291, 0.77254769]])

In [67]:
np.random.randint(100)

73

In [68]:
np.random.randint(1,10,size=5)

array([7, 7, 7, 6, 2])

In [69]:
np.random.randint(1,20,size=(2,3))

array([[17, 11, 11],
       [ 5,  6,  6]])

In [70]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
np.arange(3,15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
np.arange(3,15,2)

array([ 3,  5,  7,  9, 11, 13])

In [76]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [77]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
y = np.where(arr<6,arr,99)
y

array([ 0,  1,  2,  3,  4,  5, 99, 99, 99, 99, 99, 99])

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [80]:
np.clip(arr,3,9)

array([3, 3, 3, 3, 4, 5, 6, 7, 8, 9, 9, 9])

In [82]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [85]:
arr2 = arr.reshape((2,3))
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [89]:
arr2.shape

(2, 3)

In [90]:
arr3 = np.transpose(arr2)
arr3

array([[0, 3],
       [1, 4],
       [2, 5]])

In [91]:
arr3.shape

(3, 2)

In [92]:
# ceil() and floor()

arr = np.array([1.2,3.4,5.2,6.3,9.1,7.7])
arr

array([1.2, 3.4, 5.2, 6.3, 9.1, 7.7])

In [93]:
np.ceil(arr)

array([ 2.,  4.,  6.,  7., 10.,  8.])

In [94]:
np.floor(arr)

array([1., 3., 5., 6., 9., 7.])

In [95]:
arr = np.array([[1,2,3],[4,5,6]])
total = np.sum(arr)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
total

21

In [97]:
np.sum(arr,axis=0)

array([5, 7, 9])

In [98]:
np.sum(arr,axis=1)

array([ 6, 15])

In [99]:
np.mean(arr)

3.5

In [100]:
np.mean(arr,axis=0)

array([2.5, 3.5, 4.5])

In [101]:
np.mean(arr,axis=1)

array([2., 5.])

In [103]:
np.median(arr,axis=0)

array([2.5, 3.5, 4.5])

In [104]:
np.min(arr)

1

In [105]:
np.max(arr)

6

In [107]:
np.min(arr,axis=1)

array([1, 4])

In [108]:
np.std(arr)

1.707825127659933

In [109]:
np.var(arr)

2.9166666666666665

In [111]:
arr = np.array([[1,4,9],[16,25,36]])
np.sqrt(arr)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [113]:
arr= np.array([[3,4,5],[5,6,3]])
arr

array([[3, 4, 5],
       [5, 6, 3]])

In [114]:
np.unique(arr)

array([3, 4, 5, 6])

In [115]:
arr.flatten()

array([3, 4, 5, 5, 6, 3])

In [116]:
np.prod(arr)

5400

In [117]:
np.prod(arr,axis=0)

array([15, 24, 15])

In [118]:
np.prod(arr,axis=1)

array([60, 90])