#**1. BASICS OF NUMPY**

## IMPORTING NUMPY PACKAGE

In [ ]:
#Import NumPy Module
import numpy as np

##CREATING AN NUMPY ARRAY

In [ ]:
# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])
print('x = ', x)

x =  [1 2 3 4 5]


##FUNCTIONS AVAILABLE IN NUMPY PACKAGE

In [ ]:
# We print x
print('x = ', x)
print()

# Information -> X
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [1 2 3 4 5]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


##TYPECASTING

In [ ]:
x = np.array([1, 2, 'World'])

# We print the ndarray
print()
print('x = ', x)
print()

# Information -> X
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)   # this proves on how type casting is done


x =  ['1' '2' 'World']

x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U21


##2-D ARRAY

In [ ]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# Display Y
print()
print('Y = \n', Y)
print()

# Information -> Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)


Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


##UPCASTING

In [ ]:
# Elements - Integer
x = np.array([1,2,3])

# Elements - Float
y = np.array([-2.0,2.0,3.0])

# Elements - Integer & Float
z = np.array([1, 6.4, 100])

# Display - dtype
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int64
The elements in y are of type: float64
The elements in z are of type: float64


##ASSIGNING DATA TYPE

In [ ]:
x = np.array([1.5, 2, 3.7, -4.0, 5.9], dtype = np.int64)

#Display X
print()
print('x = ', x)
print()

#Type of X
print('The elements in x are of type:', x.dtype)


x =  [ 1  2  3 -4  5]

The elements in x are of type: int64


#**2. SPECIALIZED NUMPY ARRAY FUNCTIONS**

##ZEROES

In [ ]:
#Create an array of Zeroes
X = np.zeros((3,4) ,dtype = np.int64)

#Display X
print()
print('X = \n', X)
print()


X = 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]



##ONES

In [ ]:
#Create an array of Ones
X = np.ones((5) ,dtype = np.int64)

#Display X
print()
print('X = \n', X)
print()


X = 
 [1 1 1 1 1]



##EYE

In [ ]:
#Create a Identity Matrix
X = np.eye(4 ,dtype = np.int64)

#Display X
print()
print('X = \n', X)
print()


X = 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]



##DIAG

In [ ]:
#Create a diagonal matrix

X = np.diag([100,20,-30,66])

#Display X
print()
print('X = \n', X)
print()


X = 
 [[100   0   0   0]
 [  0  20   0   0]
 [  0   0 -30   0]
 [  0   0   0  66]]



##ARANGE

In [ ]:
#Create a numpy array similar to list as similar to using range function
x = np.arange(-10,18,4)

#Display x
print()
print('x = ', x)
print()


x =  [-10  -6  -2   2   6  10  14]



##RESHAPE

In [ ]:
#Create a numpy array of numbers from 0 -> 19
x = np.arange(-10,10)

#Display x - intial
print('Length of x: ',len(x))
print('Original x = ', x)
print()

#Reshape x using reshape() function
x = np.reshape(x, (5,4))

#Display x - Reshaped
print()
print('Reshaped x = \n', x)
print()

Length of x:  20
Original x =  [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]


Reshaped x = 
 [[-10  -9  -8  -7]
 [ -6  -5  -4  -3]
 [ -2  -1   0   1]
 [  2   3   4   5]
 [  6   7   8   9]]



Or using the a lot simpler syntax

In [ ]:
y = np.arange(-10,10).reshape(5, 4)

#Display y - Reshaped
print()
print('Reshaped y = \n', y)
print()


Reshaped y = 
 [[-10  -9  -8  -7]
 [ -6  -5  -4  -3]
 [ -2  -1   0   1]
 [  2   3   4   5]
 [  6   7   8   9]]



#RANDOM NUMPY ARRAYS

##RANDOM ARRAYS

In [ ]:
#import random module
import random

#Create a 2 X 3 random numpy array
X = np.random.random((4,3))

#Display X
print()
print('X = \n', X)
print()


X = 
 [[0.31323818 0.4949697  0.40365   ]
 [0.76079057 0.23195748 0.36662976]
 [0.01896202 0.06507374 0.33161108]
 [0.64489379 0.67417641 0.42258326]]



In [ ]:
#Use randint function
X = np.random.randint(-10,10,size=(4,3))

#Display
print()
print('X = \n', X)
print()


X = 
 [[ -8   2  -1]
 [ -8   0  -9]
 [  1   8   1]
 [-10   5 -10]]



#ACCESSING ELEMENTS

##INDEXING

In [ ]:
#Create a numpy array
x = np.arange(1,6)

#Display x
print()
print('x = ', x)
print()

#Accessing - Positive Indexing
print('First Element in x:', x[0])
print('Second Element in x:', x[1])
print('Last Element in x:', x[4])
print()

#Accessing - Positive Indexing
print('First Element in x:', x[-5])
print('Second Element in x:', x[-4])
print('Fifth (Last) Element in x:', x[-1])

#Accessing - Range Indexing
print('Elements within: ', x[2:5])
print('Elements within: ', x[-2:-5:-1])


x =  [1 2 3 4 5]

First Element in x: 1
Second Element in x: 2
Last Element in x: 5

First Element in x: 1
Second Element in x: 2
Fifth (Last) Element in x: 5
Elements within:  [3 4 5]
Elements within:  [4 3 2]


##MODIFYING NDARRAYS

In [ ]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Display X - initial
print()
print('X = \n', X)
print()

#Modification
X[0,0] = 17
X[2,2] = -9
X[1,0] = 99

# Let's access some elements in X
print('Modified (0,0) Element:', X[0,0])
print('Modified (0,1) Element:', X[1,0])
print('Modified (2,2) Element:', X[2,2])

#Display X - Modified
print()
print('X = \n',X)
print()


X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified (0,0) Element: 17
Modified (0,1) Element: 99
Modified (2,2) Element: -9

X = 
 [[17  2  3]
 [99  5  6]
 [ 7  8 -9]]



#ADDING AND DELETING ELEMENTS OF ARRAY

##DELETING

In [ ]:
#Create an 1D-numpy array
x = np.arange(1,6)

#Create a 2D-numpy array
Y = np.arange(1,10).reshape(3,3)

#Display X - initial
print()
print('Original x = ', x)

#Delete the first and last element of X
x = np.delete(x, [0,4])

#Display X - modified
print()
print('Modified x = ', x)

#Display Y - initial
print()
print('Original Y = \n', Y)

#Delete First row of Y and store in w
w = np.delete(Y, 0, axis=0)

#Delete First and Last column and store in v
v = np.delete(Y, [0,2], axis=1)

#Display Y - modified -> w
print()
print('w = \n', w)

#Display Y - modified -> v
print()
print('v = \n', v)


Original x =  [1 2 3 4 5]

Modified x =  [2 3 4]

Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

w = 
 [[4 5 6]
 [7 8 9]]

v = 
 [[2]
 [5]
 [8]]


##APPEND

In [ ]:
#Create a 1D-numpy array
x = np.array([1, 2, 3, 4, 5])

#Create a 2D-numpy array
Y = np.array([[1,2,3],[4,5,6]])

#Display x - initial
print()
print('Original x = ', x)

#Append integer-6 to array 6
x = np.append(x, 6)

#Display x - Appended 1st
print()
print('x = ', x)

#Append integer- 7 and 8 to x
x = np.append(x, [7,8])

#Display x - Appended 2nd time
print()
print('x = ', x)

#Display y - initial
print()
print('Original Y = \n', Y)

#Append a new row containing integers 7, 8 and 9
#axis -> 0 : Rows
v = np.append(Y, [[7,8,9]], axis=0)

#Append a new column containing integers 9 and 10
#axis -> 0 : Columns
q = np.append(Y,[[9],[10]], axis=1)

#Display y - modified -> stored in v
print()
print('v = \n', v)

#Display y - modeified -> stored in q
print()
print('q = \n', q)


Original x =  [1 2 3 4 5]

x =  [1 2 3 4 5 6]

x =  [1 2 3 4 5 6 7 8]

Original Y = 
 [[1 2 3]
 [4 5 6]]

v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

q = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]


##INSERTING (CONTD.)

In [ ]:
#Create a 1D-numpy array
x = np.array([-2, -1, 2, 3, 4])

#Create a 2D-numpy array
Y = np.array([[1,2,3],[7,8,9]])

#Display X - initial
print()
print('Original x = ', x)

#Insert integers 0 and 1 at index 2
x = np.insert(x,2,[0, 1])

#Display X - modified
print()
print('x = ', x)

#Display y - initial
print()
print('Original Y = \n', Y)

#Insert a row between initial and final rows
#axis -> 0 : Rows
w = np.insert(Y,1,[4,5,6],axis=0)

#Insert a column at position containing only 5's
#axis -> 1 : Columns
v = np.insert(Y,1,5, axis=1)

#Display w - modified y
print()
print('w = \n', w)

#Display v - modified y
print()
print('v = \n', v)


Original x =  [-2 -1  2  3  4]

x =  [-2 -1  0  1  2  3  4]

Original Y = 
 [[1 2 3]
 [7 8 9]]

w = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

v = 
 [[1 5 2 3]
 [7 5 8 9]]


##H-STACK & V-STACK

In [ ]:
#Create a 1D-numpy array
x = np.array([1,2])

#Create a 2D-numpy array
Y = np.array([[3,4],[5,6]])

#Display x - initial
print()
print('x = ', x)

#Display y - initial
print()
print('Y = \n', Y)

#Use vstack function
#vstack -> vertical stacking
z = np.vstack((x,Y))

#Use hstack function
#hstack -> horizontal stacking
w = np.hstack((Y,x.reshape(2,1)))

#Display z
print()
print('z = \n', z)

#Display w
print()
print('w = \n', w)


x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]


#SORTING

##SORT - FUNCTION

In [ ]:
#Create a 1D random numpy array
x = np.random.randint(1,11,size=(10,))

#Display x - initial
print()
print('Original x = ', x)

#Sort array x using sort() as a function
print()
print('Sorted x (out of place):', np.sort(x))

#Display x - after sorting (keenly see the O/P)
print()
print('x after sorting:', x)


Original x =  [ 2  5  1  5  6  9  1 10  6  3]

Sorted x (out of place): [ 1  1  2  3  5  5  6  6  9 10]

x after sorting: [ 2  5  1  5  6  9  1 10  6  3]


##SORT - METHOD

In [ ]:
#Create a 1D- random numpy array
x = np.random.randint(-10,20,size=(10,))

#Display x - initial
print()
print('Original x = ', x)

#Sort array x using sort() as a method
x.sort()

#Display x - after sorting (see the difference)
print()
print('x after sorting:', x)


Original x =  [ 9  4 17 -2 18  4 15  9  2 -1]

x after sorting: [-2 -1  2  4  4  9  9 15 17 18]


#SET OPERATIONS

##UNION

In [ ]:
#Create a 1D-numpy array
x = np.array([1,2,3,4,5])

#Create a 1D-numpy array
y = np.array([6,7,2,8,4])

#Display x - initial
print()
print('x = ', x)

#Display y - initial
print()
print('y = ', y)

#Use the union1d function to perform union operation
print()
print('All the elements of x and y:',np.union1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

All the elements of x and y: [1 2 3 4 5 6 7 8]


##SET DIFFERENCE

In [ ]:
#Create a 1D-numpy array
x = np.array([1,2,3,4,5])

#Create a 1D-numpy array
y = np.array([6,7,2,8,4])

#Display x - initial
print()
print('x = ', x)

#Display y - initial
print()
print('y = ', y)

#Use the setdiff1d function to perform set-differnece operation
print()
print('All the elements of x and y:',np.setdiff1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

All the elements of x and y: [1 3 5]


##INTERSECTION

In [ ]:
#Create a 1D-numpy array
x = np.array([1,2,3,4,5])

#Create a 1D-numpy array
y = np.array([6,7,2,8,4])

#Display x - initial
print()
print('x = ', x)

#Display y - initial
print()
print('y = ', y)

#Use the intersect1d function to perform intersection operation
print()
print('All the elements of x and y:',np.intersect1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

All the elements of x and y: [2 4]


#BROADCASTING

**Broadcasting**
 is NumPy’s ability to process ndarrays of different sizes as if all were the same size (different to a list).
It permits an elegant way of adding a scalar to a vector adds the scalar value to each and every element.

In [ ]:
#Create 1D-numpy array
x = np.array([1,2,3])

#Create a 3 x 3 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

#Create a 3 x 1 ndarray
Z = np.array([1,2,3]).reshape(3,1)

#Display x - initial
print()
print('x = ', x)
print()

#Display y - initial
print()
print('Y = \n', Y)
print()

#Display z - initial
print()
print('Z = \n', Z)
print()

#Performing broadcasting operations - see the O/P keenly to understand broadcasting
print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)


x =  [1 2 3]


Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Z = 
 [[1]
 [2]
 [3]]

x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


#MATHEMATICAL OPERATIONS

##ADD, SUB, MUL & DIV

In [ ]:
#Create two 1D-numpy array
x = np.array([0,1,2,3,4])
y = np.array([5.5,-6.5,-4,7.5,8])

#Display x - initial
print()
print('x = ', x)

#Display y - initial
print()
print('y = ', y)
print()

#Perform basic arithmetic operations like Addition, Subtraction, Multiplication and Division.
#Instead of using +, -, *, / we can use add(), subtract(), multiply() and divide()
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))


x =  [0 1 2 3 4]

y =  [ 5.5 -6.5 -4.   7.5  8. ]

x + y =  [ 5.5 -5.5 -2.  10.5 12. ]
add(x,y) =  [ 5.5 -5.5 -2.  10.5 12. ]

x - y =  [-5.5  7.5  6.  -4.5 -4. ]
subtract(x,y) =  [-5.5  7.5  6.  -4.5 -4. ]

x * y =  [ 0.  -6.5 -8.  22.5 32. ]
multiply(x,y) =  [ 0.  -6.5 -8.  22.5 32. ]

x / y =  [ 0.         -0.15384615 -0.5         0.4         0.5       ]
divide(x,y) =  [ 0.         -0.15384615 -0.5         0.4         0.5       ]


#BOOLEAN INDEXING

In [ ]:
#reate a 5 X 5 np array of integers ranging from 0 to 24
X = np.arange(25).reshape(5, 5)

#Display X - initial
print()
print('Original X = \n', X)
print()

#Use Boolean indexing pick certain elements from X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

#Using Boolean indexing to assign the elements between 11 and 19 as -1
X[(X > 11) & (X < 19)] = -1

#Display x - modified
print()
print('X = \n', X)
print()


Original X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 -1 -1 -1]
 [-1 -1 -1 -1 19]
 [20 21 22 23 24]]

