In [3]:
import numpy as np

In [ ]:
a = np.array([1,2,3],dtype='int32')
a

NameError: ignored

In [ ]:
b=np.array([[3,4,5],[6,7,8]])
print(b)

[[3 4 5]
 [6 7 8]]


In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
a.shape

(3,)

In [ ]:
b.shape

(2, 3)

In [ ]:
a.dtype

dtype('int32')

In [ ]:
type(a)

numpy.ndarray

In [ ]:
b.size

6

In [ ]:
a.itemsize

4

In [ ]:
a.nbytes

12

access/change specific elements , rows, column

In [ ]:
a =np.array([[1,2,3,4,5,6,7],[8,9,10,111,12,13,14]])
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10 111  12  13  14]]


In [ ]:
a[1,5]

13

In [ ]:
a[0,4]

5

In [ ]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[1,:]

array([  8,   9,  10, 111,  12,  13,  14])

In [ ]:
a[:,2]

array([ 3, 10])

In [ ]:
a[0,1:-1:2]

array([2, 4, 6])

In [ ]:
a[1,5] =20
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10 111  12  20  14]]


In [ ]:
a[:,2]

array([ 3, 10])

In [ ]:
a[:,2]= [21,22]

In [ ]:
print(a)

[[  1   2  21   4   5   6   7]
 [  8   9  22 111  12  20  14]]


In [ ]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
b[0,1,:]

array([3, 4])

In [ ]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
b[0,1,1]

4

In [ ]:
b[:,1,:] = [[91,92],[93,94]]

In [ ]:
b

array([[[ 1,  2],
        [91, 92]],

       [[ 5,  6],
        [93, 94]]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# random numbers between 0 and 1
np.random.rand()

0.15804624227694408

In [ ]:
np.random.rand(4,2)

array([[0.27412868, 0.71297607],
       [0.64108671, 0.43680052],
       [0.06442624, 0.56535485],
       [0.02611337, 0.22650218]])

In [ ]:
# random integer values below the given number
np.random.randint(100)

68

In [ ]:
np.random.randint(4,7,size=(3,3)) # random values between the given numbers

array([[4, 5, 5],
       [6, 6, 6],
       [4, 4, 5]])

In [ ]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr , 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
arr =np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
arr + 2

array([3, 4, 5, 6])

In [ ]:
arr-2

array([-1,  0,  1,  2])

In [ ]:
arr * 2

array([2, 4, 6, 8])

In [ ]:
arr /2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
brr = np.array([1,0,2,0])

In [ ]:
arr +brr

array([2, 2, 5, 4])

In [ ]:
arr ** 2

array([ 1,  4,  9, 16])

In [ ]:
#stats

astat = np.array([[1,2,3,0],[4,5,6,7]])
astat

array([[1, 2, 3, 0],
       [4, 5, 6, 7]])

In [ ]:
np.min(astat)

0

In [ ]:
np.min(astat,axis=1)

array([0, 4])

In [ ]:
np.max(astat)

7

In [ ]:
np.max(astat,axis=1)

array([3, 7])

In [ ]:
np.sum(astat)

28

In [ ]:
np.sum(astat,axis = 0)

array([5, 7, 9, 7])

In [ ]:
np.sum(astat,axis=1)

array([ 6, 22])

In [ ]:
before = astat.copy()
before

array([[1, 2, 3, 0],
       [4, 5, 6, 7]])

In [ ]:
after = before.reshape([8,1])

In [ ]:
after

array([[1],
       [2],
       [3],
       [0],
       [4],
       [5],
       [6],
       [7]])

In [ ]:
after = before.reshape([4,2])
after

array([[1, 2],
       [3, 0],
       [4, 5],
       [6, 7]])

In [ ]:
a1=[1,2,3,4]
a2=[1,2,3,4]
result=[(x+y) for x,y in zip(a1,a2)]
print(result)
a1+a2

[2, 4, 6, 8]


[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
a =np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])
print(a)
a.ndim

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


2

In [ ]:
a.size

12

In [ ]:
a.shape

(4, 3)

In [ ]:
a.sum()

78

In [ ]:
a.max()

12

In [ ]:
a.min()

1

In [ ]:
np.min(a)

1

In [ ]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.min(a,axis=0)

array([1, 2, 3])

In [ ]:
np.min(a,axis=1)

array([ 1,  4,  7, 10])

In [ ]:
np.max(a,axis=1)

array([ 3,  6,  9, 12])

In [ ]:
np.sum(a,axis=1)

array([ 6, 15, 24, 33])

In [ ]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [ ]:
b =np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
print(np.vstack((a,b)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
print(np.hstack((a,b)))

[[ 1  2  3  1  2  3]
 [ 4  5  6  4  5  6]
 [ 7  8  9  7  8  9]
 [10 11 12 10 11 12]]


In [ ]:
print(a.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
np.insert(arr,3,8)

array([1, 2, 3, 8, 4])

In [6]:
np.append(arr,12)

array([ 1,  2,  3,  4, 12])

In [10]:
np.delete(arr,3)

array([1, 2, 3])

In [11]:
arr

array([1, 2, 3, 4])

In [ ]:
sort_arr = np.random.randint(0,20,10)
sort_arr

array([ 3, 12,  0,  2, 12, 12,  2,  2, 16, 11])

In [ ]:
np.sort(sort_arr)

array([ 0,  2,  2,  2,  3, 11, 12, 12, 12, 16])

create an array of strings and use sort() to sort them


In [ ]:
np.array_split(sort_arr,4)

[array([ 3, 12,  0]), array([ 2, 12, 12]), array([2, 2]), array([16, 11])]

In [ ]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])