In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv('Social_Network_Ads.csv')

In [ ]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
data.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender'])

In [ ]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

In [ ]:
data.drop('User ID', axis=1, inplace=True)

In [ ]:
X = data.drop('Purchased', axis=1)
y = data['Purchased']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.25,random_state=42)

In [ ]:
#SVM model
from sklearn.svm import SVC
svmclf = SVC(kernel='linear')
svmclf.fit(X_train, y_train)

SVC(kernel='linear')

In [ ]:
y_pred = svmclf.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
print('Accuracy is: ', accuracy_score(y_test,y_pred))

Accuracy is:  0.84


In [ ]:
print(confusion_matrix(y_test, y_pred))

[[54  9]
 [ 7 30]]


In [ ]:
#Decision tree
from sklearn.tree import DecisionTreeClassifier
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train, y_train)
y_pred = dt_clf.predict(X_test)

In [ ]:
print('Accuracy is: ', accuracy_score(y_test, y_pred))

Accuracy is:  0.84


In [ ]:
print(confusion_matrix(y_test, y_pred))

[[55  8]
 [ 8 29]]


In [ ]:
#Random forest
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier()
rf_clf.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
y_pred = rf_clf.predict(X_test)

In [ ]:
print('Accuracy is: ', accuracy_score(y_test, y_pred))

Accuracy is:  0.9


In [ ]:
print(confusion_matrix(y_test, y_pred))

[[58  5]
 [ 5 32]]


In [ ]:
#Hyper parameter tuning
rf_clf1 = RandomForestClassifier(n_estimators=20, max_depth=20, criterion='entropy', min_samples_split=3)
rf_clf1.fit(X_train, y_train)


# n_estimators= The required number of trees in the Random Forest. The default value is 10. We can choose any number but need to take care of the overfitting issue.
# criterion= It is a function to analyze the accuracy of the split. Here we have taken "entropy" for the information gain.

RandomForestClassifier(criterion='entropy', max_depth=20, min_samples_split=3,
                       n_estimators=20)

In [ ]:
y_pred = rf_clf1.predict(X_test)

In [ ]:
print('Accuracy is: ', accuracy_score(y_test, y_pred))

Accuracy is:  0.9
